name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: PyInstaller Action
      uses: Martin005/pyinstaller-action@v1.2.0
      with:
        python_ver: '3.12.6'
        spec: 'src/main.spec'
        requirements: 'src/requirements.txt'
        upload_exe_with_name: 'My executable'
        options: --onefile, --add-data "assets:assets", --name "Jack The last warrior", --windowed 
